# Generated by Django 3.2.20 on 2023-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230801_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_story_id',
            field=models.IntegerField(null=True),
        ),
    ]
